<?php

/**
 * Implementation of hook_block_info().
 */
function maav_login_block_block_info() {
  $blocks = array();

  $blocks['maav_login'] = array(
    'info' => t('MAAV Login Block'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

function maav_login_block_block_view($delta = '') {
  global $user;
  $block = array();

  switch ($delta) {
    case 'maav_login':
      if (!$user->uid) {
        $block['content'] = l(t('Login'), 'user');
      }
      break;
  }
  return $block;
}

