<?php

/**
 * Implementation of hook_permission().
 */
function maav_groups_permission() {
  return array(
    'maav groups administer' => array(
      'title' => t('Administer MAAV groups features'),
      'description' => t('Currently allows you to change the "featured" group'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function maav_groups_menu() {
  $items = array();
  $items['admin/config/maav/groups'] = array(
    'title' => 'MAAV Groups Config',
    'page callback' => 'drupal_get_form',
    'page arguments' => 'maav_groups_admin_form',
    'access arguments' => 'maav groups administer',
  );

  return $items;
}

function maav_groups_admin_form($form_state) {
  $form['maav_groups_admin'] = array(
    '#type' => 'fieldset',
    '#title' => t('MAAV Groups Admin Settings'),
  );

  $form['maav_groups_admin']['maav_group_team_leads'] = array(
    '#type' => 'select',
    '#title' => t('MAAV Team Leads'),
    '#default_value' => variable_get('maav_group_team_leads', ''),
    '#options' => og_label_multiple(og_get_all_group()),  
  );

  return system_settings_from($form);
}

